development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  timeout: 5000
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  timeout: 5000
  username: ubuntu
  password: